# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       xorg-x11-drv-keyboard

# >> macros
# << macros

Summary:    Xorg X11 keyboard input driver
Version:    1.6.2
Release:    1
Group:      Graphics/X11
License:    MIT
URL:        http://www.x.org/
Source0:    http://xorg.freedesktop.org/releases/individual/driver/xf86-input-keyboard-%{version}.tar.bz2
Source100:  xorg-x11-drv-keyboard.yaml
Requires:   xorg-x11-server-Xorg
Requires:   xkeyboard-config
BuildRequires:  pkgconfig(xorg-macros) >= 1.8
BuildRequires:  pkgconfig(xorg-server) >= 1.4
BuildRequires:  pkgconfig(xproto)
BuildRequires:  pkgconfig(inputproto)

%description
Xorg X11 keyboard input driver.


%prep
%setup -q -n xf86-input-keyboard-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post


%files
%defattr(-,root,root,-)
# >> files
%(pkg-config xorg-server --variable=moduledir )/input/kbd_drv.so
%doc %{_mandir}/man4/kbd.4*
# << files
